---
name: Jellyfin Server
version: 1.1.3
slug: jellyfinserver
description: Jellyfin Server add-on
url: https://github.com/PrimusNZ/addon-jellyfin
webui: http://[HOST]:[PORT:8096]
arch:
  - aarch64
  - armv7
  - amd64
init: false
map:
  - config:rw
  - share:rw
  - media:rw
  - ssl
video: true
watchdog: http://[HOST]:8096/health
host_network: true
image: ghcr.io/primusnz/hassio-addons/{arch}-jellyfin-server